### PR TITLE
fix: Avoid including InfoSource.plist to compile sources

### LINKED ISSUE #9: Xcode 11 compilation error because of plist inclusion to compilation sources
It seems Xcode 11 beta 6 complains about including plist into the compile sources build phase. I guess we can just remove it from the compile sources list

EDIT: Just tried to remove plist from compile sources to make sure that was the problem, and it works. I will do a pull request with the fix

```
1) Target 'BSGridCollectionViewLayout' (project 'Pods') has copy command from '/ios-app/Pods/BSGridCollectionViewLayout/Sources/InfoSource.plist' to '/Library/Developer/Xcode/DerivedData/IOSAPP-hhwqkvqhhakfhgbegnyfmpxvohva/Build/Products/Beta_debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/InfoSource.plist'
```

### PR DESCRIPTION
**Pull request by ruizmarc**
fixes https://github.com/mikaoj/BSGridCollectionViewLayout/issues/9 and bumps version to 1.2.5 :)

### CODE REVIEW

**Comment by ruizmarc** [comment]
Thanks for accepting the pull request! 🙌

Can we get the new pod version published on Cocoapods? :)

Thanks in advanced!

Btw, it would be great to get BSImagePicker dependency also updated so it can be used in XCode 11 :)

**Comment by mikaoj** [comment]
Sure!

The develop branch builds in Xcode 11, but it's probably still missing features you need ;)

I would happily review a pull-request that fixes whatever needs to be fixed for master to build in Xcode 11 as well ^^

**Comment by mikaoj** [comment]
1.2.5 is tagged and pushed to cocoapods podspec repo

**Comment by mikaoj** [comment]
Thanks :)

**Pull request merged**
